import type { DoctorReport, ProbeResult, TestResult } from "./domain/types.ts";

const STATUS_MARK = {
  AVAILABLE: "+",
  NOT_INSTALLED: "-",
  UNEXECUTABLE: "!",
  UNSUPPORTED_VERSION: "!",
  PASS: "+",
  ASSERTION_FAILED: "x",
  TIMEOUT: "!",
  RUNTIME_DEGRADED: "!",
  HARNESS_ERROR: "x",
} as const;

export function formatProbe(result: ProbeResult): string {
  const version = result.version ? ` (${result.version})` : "";
  const diagnostic = result.diagnostic ? `\n  ${result.diagnostic}` : "";
  return `[${STATUS_MARK[result.status]}] ${result.runtime}: ${result.status}${version}${diagnostic}`;
}

export function formatTest(result: TestResult): string {
  const lines = [
    `[${STATUS_MARK[result.status]}] ${result.runtime}: ${result.status}`,
    `  duration: ${Math.round(result.durationMs)}ms`,
    `  isolated workspace cleaned: ${result.isolation.cleaned ? "yes" : "no"}`,
  ];
  if (result.evidence) {
    lines.push(`  canary: ${result.evidence.tokenMatched ? "matched" : "missing"}`);
  }
  if (result.diagnostic) lines.push(`  diagnostic: ${result.diagnostic}`);
  return lines.join("\n");
}

const DOCTOR_MARK = {
  READY: "+",
  DEGRADED: "!",
  UNAVAILABLE: "-",
  UNVERIFIED: "?",
} as const;

export function formatDoctor(report: DoctorReport): string {
  const lines = [
    `Runtime Canary Doctor (${report.mode === "live" ? "live canary" : "probe only"})`,
    `${report.summary.total} runtimes checked in ${Math.round(report.durationMs)}ms`,
    [
      `${report.summary.ready} ready`,
      `${report.summary.degraded} degraded`,
      `${report.summary.unavailable} unavailable`,
      `${report.summary.unverified} unverified`,
    ].join(" | "),
    `checks: ${report.summary.checksPassed} passed | ${report.summary.checksFailed} failed | ${report.summary.checksNotRun} not run`,
    "",
  ];

  for (const runtime of report.runtimes) {
    const version = runtime.version ? ` (${runtime.version})` : "";
    lines.push(`[${DOCTOR_MARK[runtime.status]}] ${runtime.displayName}: ${runtime.status}${version}`);
    if (runtime.status === "READY") {
      lines.push(`  end-to-end task, file evidence, and cleanup passed in ${Math.round(runtime.durationMs)}ms`);
    }
    for (const item of runtime.findings) {
      lines.push(`  ${item.category}: ${item.summary}`);
      lines.push(`  next: ${item.action}`);
    }
  }

  if (report.mode === "probe") {
    lines.push("", "Run with --live to prove model access, tool use, file evidence, and cleanup.");
  }
  return lines.join("\n");
}

function markdownCell(value: string | number | null): string {
  if (value === null || value === "") return "-";
  return String(value).replace(/\s+/g, " ").replace(/\|/g, "\\|");
}

function checkLabel(status: "PASS" | "FAIL" | "NOT_RUN"): string {
  return status === "NOT_RUN" ? "Not run" : status === "PASS" ? "Pass" : "Fail";
}

export function formatDoctorMarkdown(report: DoctorReport): string {
  const lines = [
    "# Runtime Canary Doctor",
    "",
    `- Mode: ${report.mode === "live" ? "Live canary" : "Probe only"}`,
    `- Generated: ${report.generatedAt}`,
    `- Duration: ${Math.round(report.durationMs)} ms`,
    `- Runtimes: ${report.summary.total}`,
    "",
    "## Summary",
    "",
    "| Ready | Degraded | Unavailable | Unverified | Checks passed | Checks failed | Checks not run |",
    "| ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    `| ${report.summary.ready} | ${report.summary.degraded} | ${report.summary.unavailable} | ${report.summary.unverified} | ${report.summary.checksPassed} | ${report.summary.checksFailed} | ${report.summary.checksNotRun} |`,
    "",
    "## Runtimes",
    "",
    "| Runtime | Status | Version | Duration |",
    "| --- | --- | --- | ---: |",
  ];

  for (const runtime of report.runtimes) {
    lines.push(`| ${markdownCell(runtime.displayName)} | ${runtime.status} | ${markdownCell(runtime.version)} | ${Math.round(runtime.durationMs)} ms |`);
  }

  for (const runtime of report.runtimes) {
    lines.push(
      "",
      `### ${markdownCell(runtime.displayName)}`,
      "",
      "| Discovery | Launch | Task | Evidence | Cleanup |",
      "| --- | --- | --- | --- | --- |",
      `| ${checkLabel(runtime.checks.discovery)} | ${checkLabel(runtime.checks.launch)} | ${checkLabel(runtime.checks.task)} | ${checkLabel(runtime.checks.evidence)} | ${checkLabel(runtime.checks.cleanup)} |`,
    );

    if (runtime.findings.length === 0) {
      lines.push("", "All requested checks passed.");
    } else {
      lines.push("", "| Finding | Category | Result | Next action |", "| --- | --- | --- | --- |");
      for (const item of runtime.findings) {
        lines.push(`| ${markdownCell(item.code)} | ${markdownCell(item.category)} | ${markdownCell(item.summary)} | ${markdownCell(item.action)} |`);
      }
    }
  }

  lines.push(
    "",
    "---",
    "Generated by Runtime Canary. The shareable report omits raw process output, executable paths, and temporary workspace paths.",
    "",
  );
  return lines.join("\n");
}
